# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BMI_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BMI_App
pod 'IQKeyboardManager' #iOS8 and later
end
